# NodeOverlay to inform Karpenter about GPU time-slicing capacity
#
# IMPORTANT: This overlay helps Karpenter make better provisioning decisions
# by understanding that GPU instances can serve more workloads than the
# physical GPU count suggests.
#
# When time-slicing is configured on nodes (via EC2NodeClass userData),
# a single GPU can serve multiple pods. However, Karpenter doesn't know
# this until the node exists. NodeOverlay bridges this gap by telling
# Karpenter about the effective capacity BEFORE provisioning.
#
# This enables:
# - Better initial node selection (right-sizing from the start)
# - Smarter consolidation decisions
# - More accurate cost calculations
#
# The actual GPU time-slicing is configured in the EC2NodeClass userData
# using Bottlerocket's built-in NVIDIA device plugin settings.
---
# Overlay for instances with 1 GPU (g5.xlarge, g5.2xlarge, g4dn.xlarge, etc.)
# Tells Karpenter this instance can serve 4 GPU workloads
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-1gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["1"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu: 4
---
# Overlay for instances with 2 GPUs
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-2gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["2"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu: 8
---
# Overlay for instances with 4 GPUs (g5.12xlarge, p4d.24xlarge, etc.)
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-4gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["4"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu: 16
---
# Overlay for instances with 8 GPUs (p4d.24xlarge, p5.48xlarge, etc.)
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-8gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["8"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu: 32
